name: hydrateme
base: core24
version: '1.3.0'
summary: A simple desktop app to remind you to drink water
description: |
  HydrateMe runs in your system tray and periodically reminds you 
  to drink water. Uses custom looping audio until you hydrate!
grade: stable
confinement: strict

apps:
  hydrateme:
    command: usr/bin/hydrateme
    plugs: [x11, wayland, audio-playback, desktop, desktop-legacy]
    desktop: usr/share/applications/hydrateme.desktop

parts:
  hydrateme:
    plugin: python
    source: .
    python-packages:
      - PyQt6
    stage-packages:
      - libnotify-bin
      - pulseaudio-utils
  desktop-entry:
    plugin: dump
    source: .
    organize:
      usr/share/applications/hydrateme.desktop: usr/share/applications/hydrateme.desktop
